// Regenerates src/data/*.ts from ../../backend/src/data/*.ts so the Vercel
// frontend-only build still ships device/location catalogs. Plain Node, no deps.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const backend = path.resolve(here, '../../backend/src/data');
const outDir = path.resolve(here, '../src/data');
fs.mkdirSync(outDir, { recursive: true });

// Strip TS-only syntax with regexes scoped to the known helpers.
const stripDevices = (src) =>
  src
    .replace(/^import[^\n]*\n/m, '')
    .replace(/: DeviceProfile\[\]/g, '')
    .replace('function uaA(android: string, model: string, chrome: string) {', 'function uaA(android, model, chrome) {')
    .replace('function uaI(ios: string, model: string) {', 'function uaI(ios, model) {');

const devSrc = fs.readFileSync(path.join(backend, 'devices.ts'), 'utf8');
const devTmp = path.join(outDir, '.devices.tmp.mjs');
fs.writeFileSync(devTmp, stripDevices(devSrc));
const { DEVICE_PROFILES } = await import(pathToFileURL(devTmp).href);
fs.rmSync(devTmp);
fs.writeFileSync(
  path.join(outDir, 'devices.ts'),
  `// Auto-generated by scripts/gen-catalog.mjs from backend/src/data/devices.ts — static fallback for when the API is unreachable.\nexport const DEVICE_FALLBACK: any[] = ${JSON.stringify(DEVICE_PROFILES, null, 2)};\n`,
);

// Locations: ROWS literal + mapping logic reproduced via temp module.
const stripLocations = (src) =>
  src
    .replace(/^import[^\n]*\n/m, '')
    .replace(/type Row = [^\n]*\n/, '')
    .replace('const ROWS: Row[] = [', 'const ROWS = [');
const locSrc = fs.readFileSync(path.join(backend, 'locations.ts'), 'utf8');
const locBody = stripLocations(locSrc)
  .replace('function slug(s: string){', 'function slug(s){')
  .replace(': LocationProfile[] = ROWS.map', ' = ROWS.map')
  .replace('synthetic: true as const', 'synthetic: true')
  .replace('export const LOCATION_PROFILES', 'const LOCATION_PROFILES_UNUSED')
  .replace(/export const COUNTRIES[\s\S]*?;\n/, '')
  .replace(/export function locationsByIds[\s\S]*$/, '')
  .replace(/export function locationsByCountry[\s\S]*$/, '')
  + '\nexport { ROWS };\n';
const locTmp = path.join(outDir, '.locations.tmp.mjs');
fs.writeFileSync(locTmp, locBody);
const locMod = await import(pathToFileURL(locTmp).href);
fs.rmSync(locTmp);
const rows = locMod.ROWS;
if (!rows) throw new Error('could not extract ROWS');
const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
const LOCATION_PROFILES = rows.map(([country, code, region, city, tz, lang, lat, lon]) => ({ id: `${code.toLowerCase()}-${slug(city)}`, country, countryCode: code, region, city, timezone: tz, language: lang, latitude: lat, longitude: lon, synthetic: true }));
fs.writeFileSync(
  path.join(outDir, 'locations.ts'),
  `// Auto-generated by scripts/gen-catalog.mjs from backend/src/data/locations.ts — static fallback for when the API is unreachable.\nexport const LOCATION_FALLBACK: any[] = ${JSON.stringify(LOCATION_PROFILES, null, 2)};\n`,
);
console.log('catalog: devices', DEVICE_PROFILES.length, 'locations', LOCATION_PROFILES.length);
