// Auto-generated by scripts/gen-catalog.mjs from backend/src/data/devices.ts — static fallback for when the API is unreachable.
export const DEVICE_FALLBACK: any[] = [
  {
    "id": "pixel-8",
    "name": "Google Pixel 8",
    "brand": "Google",
    "model": "Pixel 8",
    "osName": "Android",
    "osVersion": "15",
    "browser": "Chrome Mobile",
    "browserVersion": "128.0",
    "screen": {
      "width": 1080,
      "height": 2400
    },
    "userAgent": "Mozilla/5.0 (Linux; Android 15; Pixel 8) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.6613.127 Mobile Safari/537.36",
    "language": "en-US",
    "timezone": "America/New_York"
  },
  {
    "id": "pixel-7",
    "name": "Google Pixel 7",
    "brand": "Google",
    "model": "Pixel 7",
    "osName": "Android",
    "osVersion": "14",
    "browser": "Chrome Mobile",
    "browserVersion": "127.0",
    "screen": {
      "width": 1080,
      "height": 2400
    },
    "userAgent": "Mozilla/5.0 (Linux; Android 14; Pixel 7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.6533.103 Mobile Safari/537.36",
    "language": "en-US",
    "timezone": "America/Los_Angeles"
  },
  {
    "id": "pixel-6",
    "name": "Google Pixel 6",
    "brand": "Google",
    "model": "Pixel 6",
    "osName": "Android",
    "osVersion": "14",
    "browser": "Chrome Mobile",
    "browserVersion": "126.0",
    "screen": {
      "width": 1080,
      "height": 2400
    },
    "userAgent": "Mozilla/5.0 (Linux; Android 14; Pixel 6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.6478.122 Mobile Safari/537.36",
    "language": "en-US",
    "timezone": "Europe/London"
  },
  {
    "id": "galaxy-s24",
    "name": "Samsung Galaxy S24",
    "brand": "Samsung",
    "model": "SM-S921B",
    "osName": "Android",
    "osVersion": "14",
    "browser": "Chrome Mobile",
    "browserVersion": "128.0",
    "screen": {
      "width": 1080,
      "height": 2340
    },
    "userAgent": "Mozilla/5.0 (Linux; Android 14; SM-S921B) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.6613.127 Mobile Safari/537.36",
    "language": "en-US",
    "timezone": "Asia/Kolkata"
  },
  {
    "id": "galaxy-s23",
    "name": "Samsung Galaxy S23",
    "brand": "Samsung",
    "model": "SM-S911B",
    "osName": "Android",
    "osVersion": "14",
    "browser": "Samsung Internet",
    "browserVersion": "26.0",
    "screen": {
      "width": 1080,
      "height": 2340
    },
    "userAgent": "Mozilla/5.0 (Linux; Android 14; SM-S911B) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/26.0 Chrome/122.0.0.0 Mobile Safari/537.36",
    "language": "en-IN",
    "timezone": "Asia/Kolkata"
  },
  {
    "id": "galaxy-a54",
    "name": "Samsung Galaxy A54",
    "brand": "Samsung",
    "model": "SM-A546E",
    "osName": "Android",
    "osVersion": "13",
    "browser": "Chrome Mobile",
    "browserVersion": "125.0",
    "screen": {
      "width": 1080,
      "height": 2340
    },
    "userAgent": "Mozilla/5.0 (Linux; Android 13; SM-A546E) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.6422.113 Mobile Safari/537.36",
    "language": "en-GB",
    "timezone": "Europe/Berlin"
  },
  {
    "id": "oneplus-12",
    "name": "OnePlus 12",
    "brand": "OnePlus",
    "model": "CPH2581",
    "osName": "Android",
    "osVersion": "14",
    "browser": "Chrome Mobile",
    "browserVersion": "128.0",
    "screen": {
      "width": 1440,
      "height": 3168
    },
    "userAgent": "Mozilla/5.0 (Linux; Android 14; CPH2581) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.6613.127 Mobile Safari/537.36",
    "language": "en-IN",
    "timezone": "Asia/Kolkata"
  },
  {
    "id": "oneplus-11",
    "name": "OnePlus 11",
    "brand": "OnePlus",
    "model": "CPH2449",
    "osName": "Android",
    "osVersion": "13",
    "browser": "Chrome Mobile",
    "browserVersion": "126.0",
    "screen": {
      "width": 1440,
      "height": 3216
    },
    "userAgent": "Mozilla/5.0 (Linux; Android 13; CPH2449) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.6478.122 Mobile Safari/537.36",
    "language": "en-US",
    "timezone": "America/New_York"
  },
  {
    "id": "xiaomi-14",
    "name": "Xiaomi 14",
    "brand": "Xiaomi",
    "model": "23127PN0CG",
    "osName": "Android",
    "osVersion": "14",
    "browser": "Chrome Mobile",
    "browserVersion": "127.0",
    "screen": {
      "width": 1220,
      "height": 2712
    },
    "userAgent": "Mozilla/5.0 (Linux; Android 14; 23127PN0CG) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.6533.103 Mobile Safari/537.36",
    "language": "en-IN",
    "timezone": "Asia/Kolkata"
  },
  {
    "id": "xiaomi-redmi-note13",
    "name": "Redmi Note 13 Pro",
    "brand": "Xiaomi",
    "model": "2312DRA50G",
    "osName": "Android",
    "osVersion": "13",
    "browser": "Chrome Mobile",
    "browserVersion": "126.0",
    "screen": {
      "width": 1220,
      "height": 2712
    },
    "userAgent": "Mozilla/5.0 (Linux; Android 13; 2312DRA50G) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.6478.122 Mobile Safari/537.36",
    "language": "hi-IN",
    "timezone": "Asia/Kolkata"
  },
  {
    "id": "motorola-edge40",
    "name": "Motorola Edge 40",
    "brand": "Motorola",
    "model": "XT2303-2",
    "osName": "Android",
    "osVersion": "13",
    "browser": "Chrome Mobile",
    "browserVersion": "126.0",
    "screen": {
      "width": 1080,
      "height": 2400
    },
    "userAgent": "Mozilla/5.0 (Linux; Android 13; XT2303-2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.6478.122 Mobile Safari/537.36",
    "language": "en-US",
    "timezone": "America/Chicago"
  },
  {
    "id": "motorola-g54",
    "name": "Moto G54",
    "brand": "Motorola",
    "model": "XT2343-2",
    "osName": "Android",
    "osVersion": "14",
    "browser": "Chrome Mobile",
    "browserVersion": "128.0",
    "screen": {
      "width": 1080,
      "height": 2400
    },
    "userAgent": "Mozilla/5.0 (Linux; Android 14; XT2343-2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.6613.127 Mobile Safari/537.36",
    "language": "en-GB",
    "timezone": "Europe/London"
  },
  {
    "id": "oppo-find-x7",
    "name": "Oppo Find X7",
    "brand": "Oppo",
    "model": "PHZ110",
    "osName": "Android",
    "osVersion": "14",
    "browser": "Chrome Mobile",
    "browserVersion": "127.0",
    "screen": {
      "width": 1264,
      "height": 2780
    },
    "userAgent": "Mozilla/5.0 (Linux; Android 14; PHZ110) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.6533.103 Mobile Safari/537.36",
    "language": "zh-CN",
    "timezone": "Asia/Shanghai"
  },
  {
    "id": "vivo-x100",
    "name": "Vivo X100",
    "brand": "Vivo",
    "model": "V2309A",
    "osName": "Android",
    "osVersion": "14",
    "browser": "Chrome Mobile",
    "browserVersion": "128.0",
    "screen": {
      "width": 1260,
      "height": 2800
    },
    "userAgent": "Mozilla/5.0 (Linux; Android 14; V2309A) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.6613.127 Mobile Safari/537.36",
    "language": "en-IN",
    "timezone": "Asia/Kolkata"
  },
  {
    "id": "realme-gt5",
    "name": "Realme GT 5",
    "brand": "Realme",
    "model": "RMX3820",
    "osName": "Android",
    "osVersion": "13",
    "browser": "Chrome Mobile",
    "browserVersion": "126.0",
    "screen": {
      "width": 1240,
      "height": 2772
    },
    "userAgent": "Mozilla/5.0 (Linux; Android 13; RMX3820) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.6478.122 Mobile Safari/537.36",
    "language": "en-IN",
    "timezone": "Asia/Kolkata"
  },
  {
    "id": "nothing-phone2",
    "name": "Nothing Phone (2)",
    "brand": "Nothing",
    "model": "A065",
    "osName": "Android",
    "osVersion": "14",
    "browser": "Chrome Mobile",
    "browserVersion": "128.0",
    "screen": {
      "width": 1080,
      "height": 2412
    },
    "userAgent": "Mozilla/5.0 (Linux; Android 14; A065) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.6613.127 Mobile Safari/537.36",
    "language": "en-GB",
    "timezone": "Europe/London"
  },
  {
    "id": "pixel-tablet",
    "name": "Pixel Tablet",
    "brand": "Google",
    "model": "Pixel Tablet",
    "osName": "Android",
    "osVersion": "14",
    "browser": "Chrome Mobile",
    "browserVersion": "127.0",
    "screen": {
      "width": 1600,
      "height": 2560
    },
    "userAgent": "Mozilla/5.0 (Linux; Android 14; Pixel Tablet) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.6533.103 Mobile Safari/537.36",
    "language": "en-US",
    "timezone": "America/New_York"
  },
  {
    "id": "galaxy-z-fold5",
    "name": "Galaxy Z Fold 5",
    "brand": "Samsung",
    "model": "SM-F946B",
    "osName": "Android",
    "osVersion": "14",
    "browser": "Chrome Mobile",
    "browserVersion": "128.0",
    "screen": {
      "width": 1812,
      "height": 2176
    },
    "userAgent": "Mozilla/5.0 (Linux; Android 14; SM-F946B) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.6613.127 Mobile Safari/537.36",
    "language": "en-US",
    "timezone": "America/Los_Angeles"
  },
  {
    "id": "oneplus-nord3",
    "name": "OnePlus Nord 3",
    "brand": "OnePlus",
    "model": "CPH2491",
    "osName": "Android",
    "osVersion": "13",
    "browser": "Chrome Mobile",
    "browserVersion": "125.0",
    "screen": {
      "width": 1240,
      "height": 2772
    },
    "userAgent": "Mozilla/5.0 (Linux; Android 13; CPH2491) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.6422.113 Mobile Safari/537.36",
    "language": "en-IN",
    "timezone": "Asia/Dubai"
  },
  {
    "id": "xiaomi-poco-f5",
    "name": "POCO F5",
    "brand": "Xiaomi",
    "model": "23013PC75G",
    "osName": "Android",
    "osVersion": "13",
    "browser": "Chrome Mobile",
    "browserVersion": "126.0",
    "screen": {
      "width": 1080,
      "height": 2400
    },
    "userAgent": "Mozilla/5.0 (Linux; Android 13; 23013PC75G) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.6478.122 Mobile Safari/537.36",
    "language": "en-SG",
    "timezone": "Asia/Singapore"
  },
  {
    "id": "iphone-15-pro",
    "name": "iPhone 15 Pro",
    "brand": "Apple",
    "model": "iPhone 15 Pro",
    "osName": "iOS",
    "osVersion": "17.4",
    "browser": "Safari",
    "browserVersion": "17.0",
    "screen": {
      "width": 1179,
      "height": 2556
    },
    "userAgent": "Mozilla/5.0 (iPhone; CPU iPhone OS 17_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1",
    "language": "en-US",
    "timezone": "America/New_York"
  },
  {
    "id": "iphone-15",
    "name": "iPhone 15",
    "brand": "Apple",
    "model": "iPhone 15",
    "osName": "iOS",
    "osVersion": "17.4",
    "browser": "Safari",
    "browserVersion": "17.0",
    "screen": {
      "width": 1179,
      "height": 2556
    },
    "userAgent": "Mozilla/5.0 (iPhone; CPU iPhone OS 17_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1",
    "language": "en-US",
    "timezone": "America/Los_Angeles"
  },
  {
    "id": "iphone-14",
    "name": "iPhone 14",
    "brand": "Apple",
    "model": "iPhone 14",
    "osName": "iOS",
    "osVersion": "17.0",
    "browser": "Safari",
    "browserVersion": "17.0",
    "screen": {
      "width": 1170,
      "height": 2532
    },
    "userAgent": "Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1",
    "language": "en-GB",
    "timezone": "Europe/London"
  },
  {
    "id": "iphone-13",
    "name": "iPhone 13",
    "brand": "Apple",
    "model": "iPhone 13",
    "osName": "iOS",
    "osVersion": "16.6",
    "browser": "Safari",
    "browserVersion": "16.0",
    "screen": {
      "width": 1170,
      "height": 2532
    },
    "userAgent": "Mozilla/5.0 (iPhone; CPU iPhone OS 16_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1",
    "language": "en-US",
    "timezone": "America/Chicago"
  },
  {
    "id": "iphone-se",
    "name": "iPhone SE (3rd gen)",
    "brand": "Apple",
    "model": "iPhone SE",
    "osName": "iOS",
    "osVersion": "17.4",
    "browser": "Safari",
    "browserVersion": "17.0",
    "screen": {
      "width": 750,
      "height": 1334
    },
    "userAgent": "Mozilla/5.0 (iPhone; CPU iPhone OS 17_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1",
    "language": "en-US",
    "timezone": "America/New_York"
  },
  {
    "id": "ipad-pro-12",
    "name": "iPad Pro 12.9\"",
    "brand": "Apple",
    "model": "iPad Pro",
    "osName": "iOS",
    "osVersion": "17.4",
    "browser": "Safari",
    "browserVersion": "17.0",
    "screen": {
      "width": 2048,
      "height": 2732
    },
    "userAgent": "Mozilla/5.0 (iPad; CPU OS 17_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1",
    "language": "en-US",
    "timezone": "America/New_York"
  },
  {
    "id": "ipad-air",
    "name": "iPad Air",
    "brand": "Apple",
    "model": "iPad Air",
    "osName": "iOS",
    "osVersion": "17.0",
    "browser": "Safari",
    "browserVersion": "17.0",
    "screen": {
      "width": 1640,
      "height": 2360
    },
    "userAgent": "Mozilla/5.0 (iPad; CPU OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1",
    "language": "en-GB",
    "timezone": "Europe/London"
  }
];
